shokhov_shop/Models/Order.cs
namespace shokhov_shop.Models
{
    public class Order
    {
        public int Id { get; set; }
        public List<Set_Product> Set_Products { get; set; }
        public AppUser User { get; set; }
        public string? Full_Name { get; set; }
        public string? Telefon { get; set; }
        public string? City { get; set; }
        public int? Number_Post { get; set; }
        public bool Is_Approved { get; set; }
        public string? Comment { get; set; }
        public decimal? Total_Price { get; set; }
        public bool Confirmed_Admin { get; set; }
        public bool Completed { get; set; }
    }
}

shokhov_shop/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using shokhov_shop.Data.Enum;
using shokhov_shop.Intefaces;
using shokhov_shop.Models;
using shokhov_shop.ViewModels;

namespace shokhov_shop.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IPhotoService _photoService;
        
        public CategoryController(ICategoryRepository categoryRepository, IPhotoService photoService)
        {
            _categoryRepository = categoryRepository;
            _photoService = photoService;
        }

        public async Task<IActionResult> Woman()
        {
            // IMemoryCache Simple
            IMemoryCache cache = new MemoryCache(new MemoryCacheOptions());
            if(cache.Get<IEnumerable<Category>>("myKey") == null)
            {
                IEnumerable<Category> categories = await _categoryRepository.GetCategory(People.Women);
                cache.Set("myKey", categories, TimeSpan.FromMinutes(20));
            }
            

            var cache_category = cache.Get<IEnumerable<Category>>("myKey");
            return View(cache_category);
        }

        public async Task<IActionResult> Man()
        {
            //IMemoryCache Normal
            IMemoryCache cache = new MemoryCache(new MemoryCacheOptions());

            IEnumerable<Category> categories = await cache.GetOrCreate("myKey", async entry =>
            {
                IEnumerable<Category> categories = await _categoryRepository.GetCategory(People.Men);
                return categories;
            });
            cache.Set("myKey", categories, TimeSpan.FromMinutes(20));
            return View(categories);
        }
        //HttpCache
        [ResponseCache(Duration = 120, Location = ResponseCacheLocation.Client)]
        public async Task<IActionResult> Child()
        {
            IEnumerable<Category> categories = await _categoryRepository.GetCategory(People.Child);
            return View(categories);
        }

        public IActionResult Create()
        {
            return View("Create");
        }
            
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateOrEditCategoryViewModel categoryVM)
        {
            var result = await _photoService.AddPhotoAsync(categoryVM.Image);
            var category = new Category
            {
                Name_For_User = categoryVM.Name_For_User,
                Description = categoryVM.Description,
                People = categoryVM.People,
                Image = result.Url.ToString(),
            };
            var word = await _categoryRepository.TranslateWordAsync(category.Name_For_User);
            await _categoryRepository.WriteToResources(category.Name_For_User, word,category.People);
            word = await _categoryRepository.TranslateWordAsync(category.Description);
            await _categoryRepository.WriteToResources(category.Description, word, category.People);
            _categoryRepository.Add(category);
            return RedirectToAction("Woman");
        }
        
        public async Task<IActionResult> Edit(int id)
        {
            var category = await _categoryRepository.GetByIdAsync(id);
            var categoryVM = new CreateOrEditCategoryViewModel
            {
                Name_For_User = category.Name_For_User,
                Description = category.Description,
                URL = category.Image,
                People = category.People
            };
            return View(categoryVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,CreateOrEditCategoryViewModel categoryVM)
        {
            var editCategory = await _categoryRepository.GetByIdAsyncNoTracking(id);

            if(editCategory != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(editCategory.Image);
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(categoryVM);
                }
                if(categoryVM.Image != null)
                {
                    var photoResult = await _photoService.AddPhotoAsync(categoryVM.Image);

                    var category = new Category
                    {
                        Id = id,
                        Name_For_User = categoryVM.Name_For_User,
                        Description = categoryVM.Description,
                        People = categoryVM.People,
                        Image = photoResult.Url.ToString()
                    };
                    var word = await _categoryRepository.TranslateWordAsync(category.Name_For_User);
                    await _categoryRepository.WriteToResources(category.Name_For_User, word, category.People);
                    word = await _categoryRepository.TranslateWordAsync(category.Description);
                    await _categoryRepository.WriteToResources(category.Description, word, category.People);
                    _categoryRepository.Update(category);
                }
                else
                {
                    var category = new Category
                    {
                        Id = id,
                        Name_For_User = categoryVM.Name_For_User,
                        Description = categoryVM.Description,
                        People = categoryVM.People,
                        Image = editCategory.Image
                    };
                    var word = await _categoryRepository.TranslateWordAsync(category.Name_For_User);
                    await _categoryRepository.WriteToResources(category.Name_For_User, word, category.People);
                    word = await _categoryRepository.TranslateWordAsync(category.Description);
                    await _categoryRepository.WriteToResources(category.Description, word, category.People);
                    _categoryRepository.Update(category);
                }

                switch ((categoryVM.People)
)
                {
                    case People.Men:
                        return RedirectToAction("Man");
                    case People.Women:
                        return RedirectToAction("Woman");
                    case People.Child:
                        return RedirectToAction("Child");
                    default:
                        break;
                }

                return RedirectToAction("Woman");
            }
            return View(categoryVM);
        }
    }
}

shokhov_shop/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using shokhov_shop.Interfaces;
using shokhov_shop.Models;

namespace shokhov_shop.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly UserManager<AppUser> _userManager;

        public OrdersController(UserManager<AppUser> userManager,IOrderRepository orderRepository)
        {
            _userManager = userManager;
            _orderRepository = orderRepository;
        }

        public async Task<IActionResult> Index()
        {
            
            AppUser user = _userManager.GetUserAsync(User).Result;
            var order = await _orderRepository.Search_Order_User_Not_Confirm(user);
            if(order == null || _orderRepository.GetSet_Products(order).Count() == 0)
            {
                TempData["MyModel"] = "Вибачте але зараз ваша корзина пуста, додайте продукти та повертайтеся для оформеня замовлення.";
                return RedirectToAction("Error_Order", "Orders");
            }
            order.Set_Products = _orderRepository.GetSet_Products(order);
            order.Total_Price = _orderRepository.TotalPrice(order);
            return View(order);
        }

        public async Task<IActionResult> Remove_Product(int id)
        {
            AppUser user = _userManager.GetUserAsync(User).Result;
            var order = await _orderRepository.Search_Order_User_Not_Confirm(user);
            await _orderRepository.Remove_Product(order, id);
            return Redirect(Request.Headers["Referer"].ToString());
        }
        [HttpPost]
        public async Task<IActionResult> Buy(Order order)
        {
            AppUser user = _userManager.GetUserAsync(User).Result;
            var old_order = await _orderRepository.Search_Order_User_Not_Confirm(user);
            old_order = await _orderRepository.Update_Old_Order(old_order, order);
            
            
            _orderRepository.Update(old_order);
            return View();
        }
        public IActionResult Confirm_Order()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Add_Product(Set_Product set_Product)
        {
            if (!User.Identity.IsAuthenticated)
            {
                TempData["MyModel"] = "Вибачте але ви не війшли до свого акаунту, будь-ласка зробіть це для того що зайти до корзини або додати до неї щось!";
                return RedirectToAction("Error_Order", "Orders");
            }
            AppUser user = _userManager.GetUserAsync(User).Result;
            var order = await _orderRepository.Search_Order_User_Not_Confirm(user);
            if (order == null)
            {
                order = new Order()
                {
                    User = user,
                    Is_Approved = false,
                    
                
                };
                _orderRepository.Add(order);
            }
            await _orderRepository.Add_Product(order,set_Product);
            order.Set_Products = _orderRepository.GetSet_Products(order);
            _orderRepository.Update(order);
            return Redirect(Request.Headers["Referer"].ToString());
        }
        public IActionResult Error_Order()
        {
            if (!User.Identity.IsAuthenticated)
            {
                TempData["MyModel"] = "Вибачте але ви не війшли до свого акаунту, будь-ласка зробіть це для того що зайти до корзини або додати до неї щось!";
            }
            ViewBag.Message = TempData["MyModel"] as string;
            TempData.Remove("MyModel");
            return View();
        }

        public async Task<IActionResult> Check_Order(int? varible)
        {
            var orders = await _orderRepository.Get_isAproved_Orders();
            if(varible == 1)
            {
                return View(orders.Where(i=>i.Completed == false && i.Confirmed_Admin == true).ToList());
            }
            if(varible == 2)
            {
                return View(orders.Where(i=>i.Completed == true && i.Confirmed_Admin == true).ToList());
            }
            

            return View(orders.Where(i=>i.Confirmed_Admin == false).ToList());
        }

        public async Task<IActionResult> Confirmed_Admin(int id)
        {
            var order = await _orderRepository.Search_Order_Id(id);
            order.Confirmed_Admin = true;
            _orderRepository.Update(order);
            return Redirect(Request.Headers["Referer"].ToString());
        }
        public async Task<IActionResult> Completed(int id)
        {
            var order = await _orderRepository.Search_Order_Id(id);
            order.Completed = true;
            _orderRepository.Update(order);
            return Redirect(Request.Headers["Referer"].ToString());
        }
        public async Task<IActionResult> Detail(int id)
        {
            var order = await _orderRepository.Search_Order_Id(id);
            if (order == null || _orderRepository.GetSet_Products(order).Count() == 0)
            {
                TempData["MyModel"] = "Вибачте але зараз ваша корзина пуста, додайте продукти та повертайтеся для оформеня замовлення.";
                return RedirectToAction("Error_Order", "Orders");
            }
            order.Set_Products = _orderRepository.GetSet_Products(order);
            order.Total_Price = _orderRepository.TotalPrice(order);
            return View(order);
        }
    }
}

shokhov_shop/Controllers/SupportController.cs
using Microsoft.AspNetCore.Mvc;
using shokhov_shop.Interfaces;
using shokhov_shop.ViewModels;

namespace shokhov_shop.Controllers
{
    public class SupportController : Controller
    {
        private readonly IChatHistoryRepository _chatHistoryRepository;
        private readonly ISendGridEmail _sendGridEmail;
        public SupportController(IChatHistoryRepository chatHistoryRepository, ISendGridEmail sendGridEmail)
        {
            _chatHistoryRepository = chatHistoryRepository;
            _sendGridEmail = sendGridEmail;
        }

        public IActionResult SendMessage()
        {
            return View();
        }
        public IActionResult ChatHistory()
        {
            // Передать список сообщений в представление
            return View(_chatHistoryRepository.GetChatHistories());
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int messageId)
        {
            _chatHistoryRepository.Delete(await _chatHistoryRepository.GetMessage(messageId));
            return RedirectToAction(nameof(ChatHistory));
        }
        public IActionResult ViewMessage(int messageId)
        {
            
            return View(_chatHistoryRepository.GetMessage(messageId));
        }
        [HttpGet]
        public IActionResult SendResponse(string emailUser)
        {
             
            return View(new SendResponseViewModel() { EmailUser = emailUser});
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SendResponse(SendResponseViewModel sendResponseViewModel)
        {
            if (ModelState.IsValid)
            {
                await _sendGridEmail.SendEmailAsync(sendResponseViewModel.EmailUser, "Reset Email Confirmation", "Our response: " + sendResponseViewModel.Message);
                return RedirectToAction("SendMessage");
            }
            return View();
        }
        
       
    }
}

shokhov_shop/Views/Orders/Add_Product.cshtml
@using Microsoft.AspNetCore.Identity
@model Order

<h1>@Model.User.Email</h1>
<hi>@Model.User.UserName</hi>
@foreach(Set_Product item in Model.Set_Products)
{
    <h1>@item.Id_Product</h1>
    <h1>@item.Set_Size</h1>
    <br>
}

shokhov_shop/Views/Orders/Buy.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<link rel="stylesheet" href="~/css/support.css">

    <div class="main">  	
<input type="checkbox"  id="chk" aria-hidden="true">
<div class="signup"  >
        <form asp-action="Woman" asp-controller="Category">
            <label for="chk" aria-hidden="true">@localizer["Дякуємо за замовлення"]</label>

            <div class="sub_text">
            <p>@localizer["Дякуємо за ваше замовлення, ми відправили вам посилання для оплати на вашу єлектрону пошту. Якщо у вас будуть запитання ви можете звернутися до наших менеджерів. Гарного вам дня!"]</p>
            </div>
            <button id="sendmessage">@localizer["Повернутися на головну"]</button>
        </form>
    </div>        
</div>

shokhov_shop/Views/Orders/Check_Order.cshtml
@using System.Security.Claims
@using shokhov_shop.Models;
@model IEnumerable<Order>


@if (User.Identity.IsAuthenticated)
{
    @if (!User.IsInRole("User"))
    {
        <div class="container">

        <br />
        <div class="row">
            <div class="col-6">
                <h2 class="text-primary">Замовлення</h2>
                <div>
                              <form asp-action="Detail" asp-controller="Orders">
                                <h5>Пошук замовлення за ID  </h5>
                                <input type="text" name="id">
                                <button type="submit">Send</button>
                                <br>
                              </form>
                            </div>
            </div>
        </div>
        <br>
        <a asp-action="Check_Order" asp-controller="Orders" class="btn btn-info text-white" asp-route-varible="3">Не підтверджені замовлення</a>
        <a asp-action="Check_Order" asp-controller="Orders" class="btn btn-primary text-white" asp-route-varible="1">Замовлення на відправку</a>
        <a asp-action="Check_Order" asp-controller="Orders" class="btn btn-secondary text-white" asp-route-varible="2">Відправлені Замовлення</a>
        <div class="p-4 border rounded">
            @if (Model.Count() > 0)
            {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            Id
                        </th>
                        <th>
                            Користувач
                        </th>
                        <th>
                            Телефон
                        </th>
                        <th>
                            Фінальна ціна
                        </th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.Id
                            </td>
                            <td>
                                @item.Full_Name
                            </td>
                            <td>
                                @item.Telefon
                            </td>
                            <td>
                                @item.Total_Price
                            </td>
                            <td>
                                <div class="text-center">
                                    <form asp-action="Delete" asp-controller="Support" asp-route-messageId="@item.Id">
                                        <a asp-action="Detail" asp-route-id="@item.Id" class="btn btn-info text-white">
                                            Подивитися
                                        </a>
                                            @if(item.Confirmed_Admin == false)
                                            {
                                                <a asp-action="Confirmed_Admin" asp-route-id="@item.Id" class="btn btn-info text-white">Підтвердити</a>
                                            }
                                            @if(item.Confirmed_Admin == true && item.Completed == false){
                                                <a asp-action="Completed" asp-route-id="@item.Id" class="btn btn-info text-white">Підтвердити</a>
                                            }
                                        <button type="submit" onclick="return confirm('Are you sure you want to delete this?')"
                                                        class="btn btn-danger">
                                            Видалити
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    }
                </table>
            }
        </div>
        </div>
    }
}

shokhov_shop/Views/Orders/Detail.cshtml
@model Order
<link rel="stylesheet" href="~/css/buy_form_css.css">
<div class="row">
                    <div class="col-75">
                      <div class="container">
                        <form asp-action="Buy" asp-controller="Orders">
                          <div class="row">
                            <div class="col-50">
                              <h3>Деталі замовлення</h3>
                              <h3 class="my-3">Id замовлення: @Model.Id</h3>
                              <h3 class="my-3">ПІБ замовника: @Model.Full_Name</h3>
                              <h3 class="my-6">Телефоний номер: @Model.Telefon</h3>
                              <h3 class="my-6">Місто одержувач: @Model.City</h3>
                              <h3 class="my-6">Номер віділення "Нової Пошти": @Model.Number_Post</h3>
                              <h3 class="my-6">Коментар Замовлення: @Model.Comment</h3>
                              <h3 class="my-6">Фінальна ціна: @Model.Total_Price</h3>
                              @if(Model.Confirmed_Admin == false)
                                            {
                                                <a asp-action="Confirmed_Admin" asp-route-id="@Model.Id" class="btn btn-info text-white">Підтвердити оплату</a>
                                            }
                                            @if(Model.Confirmed_Admin == true && Model.Completed == false){
                                                <a asp-action="Completed" asp-route-id="@Model.Id" class="btn btn-info text-white">Підтвердити відправку</a>
                                            }
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  
                    <div class="col-25">
                      <div class="container">
                        <h4>Ваша корзина</h4>
                          <ul class="list_prod" id="style-1">
                            @foreach(Set_Product item in Model.Set_Products)
                            {
                                <li>
                                  <div>
                                    <div class="tex">
                                      <h5>@item.Name</h5>
                                    </div>
                                    <div class="tex">
                                      <h5>Розмір @item.Set_Size</h5>
                                    </div>
                                    <div class="tex">
                                      <h5>Ціна: @item.Price</h5>
                                    </div>
                                  </div>
                              
                                  <img src="@item.Image" alt="">
                                </li>
                            }
                            
                           
                          </ul>
                        <hr>
                        <p>Сумма замовлення: <span class="price" style="color:black"><b>@Model.Total_Price грн.</b></span></p>
                      </div>
                    </div>
                  </div>    

shokhov_shop/Views/Orders/Error_Order.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<link rel="stylesheet" href="~/css/support.css">

    <div class="main">  	
<input type="checkbox"  id="chk" aria-hidden="true">
<div class="signup"  >
        <form asp-action="Woman" asp-controller="Category">
            <label for="chk" aria-hidden="true">@localizer["Шановний користувач"]</label>

            <div class="sub_text">
                <p>@ViewBag.Message</p>
            </div>
            <button id="sendmessage">@localizer["Повернутися на головну"]</button>
        </form>
    </div>        
</div>

shokhov_shop/Views/Orders/Index.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@model Order
<link rel="stylesheet" href="~/css/buy_form_css.css">
<div class="row">
                    <div class="col-75">
                      <div class="container">
                        <form asp-action="Buy" asp-controller="Orders">
                          <div class="row">
                            <div class="col-50">
                              <h3>@localizer["Оформлення замовлення"]</h3>
                              <label >@localizer["ПІБ повністю"]</label>
                              <input type="text" asp-for="Full_Name"  placeholder="@localizer["Шевченко Тарас Григорович"]">
                              <label>@localizer["Контактний телефонний номер"]</label>
                              <input type="text" asp-for="@Model.Telefon" placeholder="+380986712487">
                              <label>@localizer["Місто куди треба доставити"]</label>
                              <input type="text" asp-for="City" placeholder="@localizer["Маріуполь"]">
                              <label >@localizer["Номер відділення Нової Пошти"]</label>
                              <input type="text" asp-for="Number_Post" placeholder="12">
                              <label>@localizer["Коментар до замовлення"]</label>
                              <textarea id="comment" asp-for="@Model.Comment" ></textarea>
                              <button>@localizer["Замовити"]</button>
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  
                    <div class="col-25">
                      <div class="container">
                        <h4>@localizer["Ваша корзина"]</h4>
                          <ul class="list_prod" id="style-1">
                            @foreach(Set_Product item in Model.Set_Products)
                            {
                                <li>
                                  <div>
                                    <div class="tex">
                                      <h5>@localizer[item.Name]</h5>
                                    </div>
                                    <div class="tex">
                                      <h5>@localizer["Розмір"] @localizer[item.Set_Size]</h5>
                                    </div>
                                    <div class="tex">
                                      <h5>Ціна: @item.Price</h5>
                                    </div>
                                    <div class="tex">
                                        <a asp-action="Remove_Product" asp-controller="Orders" asp-route-id="@item.Id">@localizer["Видалити"]</a>
                                    </div>
                                  </div>
                              
                                  <img src="@item.Image" alt="">
                                </li>
                            }
                            
                           
                          </ul>
                        <hr>
                        <p>@localizer["Сумма замовлення"]: <span class="price" style="color:black"><b>@Model.Total_Price @localizer["ГРН"].</b></span></p>
                      </div>
                    </div>
                  </div>    